### ISSUE TITLE
Set dependency to check that the media drive is accessible before starting

### ISSUE THREAD

**Issue by chris4727** [chris4727/jellyfin-container#2]
- Currently checks if the drive is available, and if it isn't marks the container as unhealthy, but it still starts the container.

# Potential examples:

# Check using external script

This is one way of doing it, but I would probably prefer to have it self-contained as in the next section.

```sh
#!/bin/bash
while ! mountpoint -q /path/in/container; do
  echo "Waiting for volume to be mounted..."
  sleep 1
done
echo "Volume is ready!"
```

- Modify your Docker Compose service to use the script: Update your docker-compose.yml to use the script. Dummy code:

```yaml
version: '3.8'
services:
  myservice:
    image: myimage
    volumes:
      - myvolume:/path/in/container
    depends_on:
      - myvolume
    command: /check_volume.sh && mycommand
    restart: unless-stopped
volumes:
  myvolume:
```

We want the myservice container to wait for the myvolume to be mounted before executing the main command (mycommand).

# Run command check without external script:

## If statement:

```yaml
version: '3'
services:
  your_service:
    image: your_image
    volumes:
      - ${MOUNTED_VOLUME_PATH}:/path/in/container
    healthcheck:
      test: ["CMD", "bash", "-c", "if [ -d ${MOUNTED_VOLUME_PATH} ]; then exit 0; else exit 1; fi"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
```

In this example:

- The healthcheck section runs a bash command to check if the directory /path/to/mounted/volume exists
- If the directory exists, the command exits with 0 (healthy); otherwise, it exits with 1 (unhealthy)
- The health check runs every 30 seconds, with a timeout of 10 seconds, and Docker will retry 3 times before marking the container as unhealthy

## While loop:

In this example, we use a while loop to continue checking until the volume is mounted. The interval, and retries is redundant, but may add a safety net.

```yaml
version: '3'
services:
  your_service:
    image: your_image
    volumes:
      - ${MOUNTED_VOLUME_PATH}:/path/in/container
    healthcheck:
      test: ["CMD-SHELL", "until [ -d ${MOUNTED_VOLUME_PATH} ]; do sleep 5; done; exit 0"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
```
